// Edit products here. Put a photo path in 'img' (e.g. "images/lipstick1.jpg") to show a real photo.
// If 'img' is empty, a drawn picture is shown automatically.

const beautyCategories = ["Sunscreen", "Lipstick", "Perfume", "Face Serum", "Moisturizer", "Face Wash", "Face Makeup", "Eye Makeup", "Hair Care", "Nails & Tools"];
const fashionCategories = ["Kurta Sets", "Sarees", "Dresses", "Tops & T-shirts", "Hoodies & Jackets", "Jeans & Pants", "Jewellery", "Handbags", "Footwear", "Activewear"];

const catInfo = {
 "Sunscreen": {
  "desc": "Helps protect your skin from sun exposure and is light enough for daily wear.",
  "points": [
   "Easy to apply, absorbs quickly",
   "Leaves no heavy or sticky feel",
   "Suitable for everyday use"
  ]
 },
 "Lipstick": {
  "desc": "A comfortable lip colour with a smooth finish that lasts through the day.",
  "points": [
   "Smooth, even colour",
   "Comfortable to wear",
   "Easy to carry in a bag"
  ]
 },
 "Perfume": {
  "desc": "A pleasant fragrance made for daily wear and special evenings.",
  "points": [
   "Fresh opening and soft base notes",
   "Long-lasting scent",
   "Elegant bottle, easy to gift"
  ]
 },
 "Face Serum": {
  "desc": "A lightweight serum that fits easily into your daily skincare routine.",
  "points": [
   "Absorbs fast, no sticky feel",
   "Use after cleansing, before moisturiser",
   "Works well under makeup"
  ]
 },
 "Moisturizer": {
  "desc": "Keeps skin soft and comfortable with a smooth, non-greasy feel.",
  "points": [
   "Light, easy to spread",
   "Good for daily morning or night use",
   "Soft finish"
  ]
 },
 "Face Wash": {
  "desc": "Cleans the skin gently and leaves it feeling fresh.",
  "points": [
   "Gentle daily cleansing",
   "Rinses off easily",
   "Fresh feel after use"
  ]
 },
 "Face Makeup": {
  "desc": "Face makeup that blends easily for a natural, even look.",
  "points": [
   "Easy to blend",
   "Comfortable all day",
   "Works for daily and party looks"
  ]
 },
 "Eye Makeup": {
  "desc": "Eye makeup that is easy to apply and made to stay put.",
  "points": [
   "Smooth, easy application",
   "Defined, bold look",
   "Easy to remove at night"
  ]
 },
 "Hair Care": {
  "desc": "Everyday hair care to keep hair soft, smooth and easy to manage.",
  "points": [
   "Easy to use at home",
   "Leaves hair soft and smooth",
   "Suits regular use"
  ]
 },
 "Nails & Tools": {
  "desc": "Handy nail and beauty essentials for your at-home routine.",
  "points": [
   "Easy to use",
   "Good quality finish",
   "Great for gifting"
  ]
 },
 "Kurta Sets": {
  "desc": "A comfortable ethnic set that works for work, festivals and family events.",
  "points": [
   "Soft, breathable fabric",
   "Comfortable fit",
   "Easy to style with jewellery"
  ]
 },
 "Sarees": {
  "desc": "A graceful saree that drapes beautifully for weddings, festivals and parties.",
  "points": [
   "Rich look and feel",
   "Comfortable to drape",
   "Blouse piece included"
  ]
 },
 "Dresses": {
  "desc": "A stylish dress that goes from day outings to evening plans.",
  "points": [
   "Flattering fit",
   "Light and comfortable",
   "Easy to dress up or down"
  ]
 },
 "Tops & T-shirts": {
  "desc": "An easy everyday top that pairs well with jeans, skirts and pants.",
  "points": [
   "Soft fabric",
   "Comfortable fit",
   "Machine washable"
  ]
 },
 "Hoodies & Jackets": {
  "desc": "A cosy layer for cooler days and casual outings.",
  "points": [
   "Warm and comfortable",
   "Easy to layer",
   "Everyday streetwear style"
  ]
 },
 "Jeans & Pants": {
  "desc": "Comfortable bottomwear that is easy to style for every day.",
  "points": [
   "Good fit and comfort",
   "Easy to match with tops",
   "Durable fabric"
  ]
 },
 "Jewellery": {
  "desc": "Lovely jewellery that adds a finishing touch to any outfit.",
  "points": [
   "Lightweight and comfortable",
   "Suits ethnic and western looks",
   "Gift-ready"
  ]
 },
 "Handbags": {
  "desc": "A practical, good-looking bag for work, college and outings.",
  "points": [
   "Roomy for daily essentials",
   "Sturdy handles or straps",
   "Easy to match with outfits"
  ]
 },
 "Footwear": {
  "desc": "Comfortable footwear designed for everyday walking and style.",
  "points": [
   "Cushioned, comfortable sole",
   "Good grip",
   "Goes with many outfits"
  ]
 },
 "Activewear": {
  "desc": "Gym and workout wear designed to move with you.",
  "points": [
   "Stretchy and comfortable",
   "Light and breathable",
   "Good for gym, yoga and running"
  ]
 }
};

const allProducts = [
  {"id": "b1", "section": "beauty", "cat": "Sunscreen", "name": "SPF 50 Matte Gel Sunscreen", "price": 299, "mrp": 339, "rating": 3.8, "reviews": 120, "color": "#aebfb0", "img": ""},
  {"id": "b2", "section": "beauty", "cat": "Sunscreen", "name": "SPF 30 Daily Moisturising Sunscreen", "price": 689, "mrp": 999, "rating": 4.5, "reviews": 251, "color": "#f2c9a5", "img": ""},
  {"id": "b3", "section": "beauty", "cat": "Sunscreen", "name": "Tinted Mineral Sunscreen SPF 40", "price": 519, "mrp": 599, "rating": 4.1, "reviews": 382, "color": "#e9a0a8", "img": ""},
  {"id": "b4", "section": "beauty", "cat": "Sunscreen", "name": "Invisible Sunscreen Stick SPF 50", "price": 349, "mrp": 509, "rating": 4.8, "reviews": 513, "color": "#cdb4c9", "img": ""},
  {"id": "b5", "section": "beauty", "cat": "Sunscreen", "name": "Hyaluronic Sunscreen SPF 50", "price": 739, "mrp": 849, "rating": 4.4, "reviews": 644, "color": "#b9c7e0", "img": ""},
  {"id": "b6", "section": "beauty", "cat": "Sunscreen", "name": "Gentle Kids Sunscreen SPF 40", "price": 579, "mrp": 839, "rating": 4.0, "reviews": 775, "color": "#c9d6c3", "img": ""},
  {"id": "b7", "section": "beauty", "cat": "Sunscreen", "name": "Oil-Free Sunscreen Lotion SPF 35", "price": 409, "mrp": 469, "rating": 4.7, "reviews": 906, "color": "#e3b66b", "img": ""},
  {"id": "b8", "section": "beauty", "cat": "Sunscreen", "name": "Sunscreen Spray SPF 50", "price": 799, "mrp": 1159, "rating": 4.3, "reviews": 1037, "color": "#d9a6a0", "img": ""},
  {"id": "b9", "section": "beauty", "cat": "Sunscreen", "name": "Aloe Calming Sunscreen Gel", "price": 629, "mrp": 719, "rating": 3.9, "reviews": 1168, "color": "#c8cdd6", "img": ""},
  {"id": "b10", "section": "beauty", "cat": "Sunscreen", "name": "Sheer Glow Sunscreen SPF 45", "price": 469, "mrp": 679, "rating": 4.6, "reviews": 1299, "color": "#d8b99a", "img": ""},
  {"id": "b11", "section": "beauty", "cat": "Lipstick", "name": "Rose Velvet Matte Lipstick", "price": 199, "mrp": 229, "rating": 4.3, "reviews": 1483, "color": "#d8b99a", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b12", "section": "beauty", "cat": "Lipstick", "name": "Berry Crush Liquid Lipstick", "price": 739, "mrp": 1069, "rating": 3.9, "reviews": 1614, "color": "#aebfb0", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b13", "section": "beauty", "cat": "Lipstick", "name": "Nude Satin Lipstick", "price": 509, "mrp": 589, "rating": 4.6, "reviews": 1745, "color": "#f2c9a5", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b14", "section": "beauty", "cat": "Lipstick", "name": "Ruby Red Long-wear Lipstick", "price": 279, "mrp": 399, "rating": 4.2, "reviews": 1876, "color": "#e9a0a8", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b15", "section": "beauty", "cat": "Lipstick", "name": "Coral Cream Lipstick", "price": 819, "mrp": 939, "rating": 3.8, "reviews": 2007, "color": "#cdb4c9", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b16", "section": "beauty", "cat": "Lipstick", "name": "Peach Tinted Lip Balm", "price": 589, "mrp": 849, "rating": 4.5, "reviews": 2138, "color": "#b9c7e0", "img": ""},
  {"id": "b17", "section": "beauty", "cat": "Lipstick", "name": "Crystal Clear Lip Gloss", "price": 349, "mrp": 399, "rating": 4.1, "reviews": 2269, "color": "#c9d6c3", "img": ""},
  {"id": "b18", "section": "beauty", "cat": "Lipstick", "name": "Plum Matte Lip Crayon", "price": 899, "mrp": 1299, "rating": 4.8, "reviews": 2400, "color": "#e3b66b", "img": ""},
  {"id": "b19", "section": "beauty", "cat": "Lipstick", "name": "Cherry Lip Stain", "price": 669, "mrp": 769, "rating": 4.4, "reviews": 2531, "color": "#d9a6a0", "img": ""},
  {"id": "b20", "section": "beauty", "cat": "Lipstick", "name": "Brick Brown Bullet Lipstick", "price": 429, "mrp": 619, "rating": 4.0, "reviews": 2662, "color": "#c8cdd6", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b21", "section": "beauty", "cat": "Perfume", "name": "Jasmine Bloom Eau de Parfum", "price": 399, "mrp": 459, "rating": 4.8, "reviews": 2846, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b22", "section": "beauty", "cat": "Perfume", "name": "Sandalwood Oud Perfume", "price": 1639, "mrp": 2379, "rating": 4.4, "reviews": 177, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b23", "section": "beauty", "cat": "Perfume", "name": "Rose Garden Eau de Toilette", "price": 1109, "mrp": 1279, "rating": 4.0, "reviews": 308, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b24", "section": "beauty", "cat": "Perfume", "name": "Citrus Fresh Body Mist", "price": 579, "mrp": 839, "rating": 4.7, "reviews": 439, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b25", "section": "beauty", "cat": "Perfume", "name": "Vanilla Musk Perfume", "price": 1819, "mrp": 2089, "rating": 4.3, "reviews": 570, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b26", "section": "beauty", "cat": "Perfume", "name": "Ocean Breeze Cologne", "price": 1289, "mrp": 1869, "rating": 3.9, "reviews": 701, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b27", "section": "beauty", "cat": "Perfume", "name": "Lavender Night Eau de Parfum", "price": 749, "mrp": 859, "rating": 4.6, "reviews": 832, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b28", "section": "beauty", "cat": "Perfume", "name": "Amber Spice Attar", "price": 1999, "mrp": 2899, "rating": 4.2, "reviews": 963, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b29", "section": "beauty", "cat": "Perfume", "name": "Floral Mini Perfume Set", "price": 1469, "mrp": 1689, "rating": 3.8, "reviews": 1094, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b30", "section": "beauty", "cat": "Perfume", "name": "Sweet Peach Body Mist", "price": 929, "mrp": 1349, "rating": 4.5, "reviews": 1225, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b31", "section": "beauty", "cat": "Face Serum", "name": "Vitamin C Brightening Serum", "price": 349, "mrp": 399, "rating": 4.2, "reviews": 1409, "color": "#f2c9a5", "img": ""},
  {"id": "b32", "section": "beauty", "cat": "Face Serum", "name": "Niacinamide 10% Serum", "price": 1089, "mrp": 1579, "rating": 3.8, "reviews": 1540, "color": "#e9a0a8", "img": ""},
  {"id": "b33", "section": "beauty", "cat": "Face Serum", "name": "Hyaluronic Acid Serum", "price": 769, "mrp": 879, "rating": 4.5, "reviews": 1671, "color": "#cdb4c9", "img": ""},
  {"id": "b34", "section": "beauty", "cat": "Face Serum", "name": "Retinol Night Serum", "price": 449, "mrp": 649, "rating": 4.1, "reviews": 1802, "color": "#b9c7e0", "img": ""},
  {"id": "b35", "section": "beauty", "cat": "Face Serum", "name": "Salicylic Acid Clear Serum", "price": 1189, "mrp": 1369, "rating": 4.8, "reviews": 1933, "color": "#c9d6c3", "img": ""},
  {"id": "b36", "section": "beauty", "cat": "Face Serum", "name": "Peptide Firming Serum", "price": 879, "mrp": 1269, "rating": 4.4, "reviews": 2064, "color": "#e3b66b", "img": ""},
  {"id": "b37", "section": "beauty", "cat": "Face Serum", "name": "Alpha Arbutin Serum", "price": 559, "mrp": 639, "rating": 4.0, "reviews": 2195, "color": "#d9a6a0", "img": ""},
  {"id": "b38", "section": "beauty", "cat": "Face Serum", "name": "Ceramide Repair Serum", "price": 1299, "mrp": 1879, "rating": 4.7, "reviews": 2326, "color": "#c8cdd6", "img": ""},
  {"id": "b39", "section": "beauty", "cat": "Face Serum", "name": "Glow Face Oil", "price": 979, "mrp": 1129, "rating": 4.3, "reviews": 2457, "color": "#d8b99a", "img": ""},
  {"id": "b40", "section": "beauty", "cat": "Face Serum", "name": "Under-Eye Serum", "price": 669, "mrp": 969, "rating": 3.9, "reviews": 2588, "color": "#aebfb0", "img": ""},
  {"id": "b41", "section": "beauty", "cat": "Moisturizer", "name": "Oil-Free Gel Moisturiser", "price": 199, "mrp": 229, "rating": 4.7, "reviews": 2772, "color": "#e9a0a8", "img": ""},
  {"id": "b42", "section": "beauty", "cat": "Moisturizer", "name": "Aloe Vera Soothing Gel", "price": 819, "mrp": 1189, "rating": 4.3, "reviews": 2903, "color": "#cdb4c9", "img": ""},
  {"id": "b43", "section": "beauty", "cat": "Moisturizer", "name": "Ceramide Barrier Cream", "price": 549, "mrp": 629, "rating": 3.9, "reviews": 234, "color": "#b9c7e0", "img": ""},
  {"id": "b44", "section": "beauty", "cat": "Moisturizer", "name": "Shea Butter Body Lotion", "price": 289, "mrp": 419, "rating": 4.6, "reviews": 365, "color": "#c9d6c3", "img": ""},
  {"id": "b45", "section": "beauty", "cat": "Moisturizer", "name": "Night Repair Cream", "price": 909, "mrp": 1049, "rating": 4.2, "reviews": 496, "color": "#e3b66b", "img": ""},
  {"id": "b46", "section": "beauty", "cat": "Moisturizer", "name": "Light Day Cream SPF 20", "price": 639, "mrp": 929, "rating": 3.8, "reviews": 627, "color": "#d9a6a0", "img": ""},
  {"id": "b47", "section": "beauty", "cat": "Moisturizer", "name": "Rose Water Hydrating Mist", "price": 379, "mrp": 439, "rating": 4.5, "reviews": 758, "color": "#c8cdd6", "img": ""},
  {"id": "b48", "section": "beauty", "cat": "Moisturizer", "name": "Cocoa Body Butter", "price": 999, "mrp": 1449, "rating": 4.1, "reviews": 889, "color": "#d8b99a", "img": ""},
  {"id": "b49", "section": "beauty", "cat": "Moisturizer", "name": "Almond Hand Cream", "price": 729, "mrp": 839, "rating": 4.8, "reviews": 1020, "color": "#aebfb0", "img": ""},
  {"id": "b50", "section": "beauty", "cat": "Moisturizer", "name": "Lip Sleeping Mask", "price": 469, "mrp": 679, "rating": 4.4, "reviews": 1151, "color": "#f2c9a5", "img": ""},
  {"id": "b51", "section": "beauty", "cat": "Face Wash", "name": "Gentle Gel Cleanser", "price": 149, "mrp": 169, "rating": 4.1, "reviews": 1335, "color": "#aebfb0", "img": ""},
  {"id": "b52", "section": "beauty", "cat": "Face Wash", "name": "Neem Foaming Face Wash", "price": 579, "mrp": 839, "rating": 4.8, "reviews": 1466, "color": "#f2c9a5", "img": ""},
  {"id": "b53", "section": "beauty", "cat": "Face Wash", "name": "Salicylic Acid Face Wash", "price": 389, "mrp": 449, "rating": 4.4, "reviews": 1597, "color": "#e9a0a8", "img": ""},
  {"id": "b54", "section": "beauty", "cat": "Face Wash", "name": "Micellar Water", "price": 209, "mrp": 299, "rating": 4.0, "reviews": 1728, "color": "#cdb4c9", "img": ""},
  {"id": "b55", "section": "beauty", "cat": "Face Wash", "name": "Cleansing Balm", "price": 639, "mrp": 729, "rating": 4.7, "reviews": 1859, "color": "#b9c7e0", "img": ""},
  {"id": "b56", "section": "beauty", "cat": "Face Wash", "name": "Charcoal Face Wash", "price": 449, "mrp": 649, "rating": 4.3, "reviews": 1990, "color": "#c9d6c3", "img": ""},
  {"id": "b57", "section": "beauty", "cat": "Face Wash", "name": "Vitamin C Face Wash", "price": 269, "mrp": 309, "rating": 3.9, "reviews": 2121, "color": "#e3b66b", "img": ""},
  {"id": "b58", "section": "beauty", "cat": "Face Wash", "name": "Clay Face Mask", "price": 699, "mrp": 1009, "rating": 4.6, "reviews": 2252, "color": "#d9a6a0", "img": ""},
  {"id": "b59", "section": "beauty", "cat": "Face Wash", "name": "Exfoliating Face Scrub", "price": 519, "mrp": 599, "rating": 4.2, "reviews": 2383, "color": "#c8cdd6", "img": ""},
  {"id": "b60", "section": "beauty", "cat": "Face Wash", "name": "Sheet Mask Pack of 5", "price": 329, "mrp": 479, "rating": 3.8, "reviews": 2514, "color": "#d8b99a", "img": ""},
  {"id": "b61", "section": "beauty", "cat": "Face Makeup", "name": "Matte Foundation", "price": 249, "mrp": 289, "rating": 4.6, "reviews": 2698, "color": "#e9a0a8", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b62", "section": "beauty", "cat": "Face Makeup", "name": "Light Skin Tint", "price": 989, "mrp": 1429, "rating": 4.2, "reviews": 2829, "color": "#cdb4c9", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b63", "section": "beauty", "cat": "Face Makeup", "name": "Full Coverage Concealer", "price": 669, "mrp": 769, "rating": 3.8, "reviews": 160, "color": "#b9c7e0", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b64", "section": "beauty", "cat": "Face Makeup", "name": "Oil Control Compact Powder", "price": 349, "mrp": 509, "rating": 4.5, "reviews": 291, "color": "#c9d6c3", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b65", "section": "beauty", "cat": "Face Makeup", "name": "Loose Setting Powder", "price": 1089, "mrp": 1249, "rating": 4.1, "reviews": 422, "color": "#e3b66b", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b66", "section": "beauty", "cat": "Face Makeup", "name": "Rose Pink Blush", "price": 779, "mrp": 1129, "rating": 4.8, "reviews": 553, "color": "#d9a6a0", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b67", "section": "beauty", "cat": "Face Makeup", "name": "Golden Glow Highlighter", "price": 459, "mrp": 529, "rating": 4.4, "reviews": 684, "color": "#c8cdd6", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b68", "section": "beauty", "cat": "Face Makeup", "name": "Smoothing Makeup Primer", "price": 1199, "mrp": 1739, "rating": 4.0, "reviews": 815, "color": "#d8b99a", "img": ""},
  {"id": "b69", "section": "beauty", "cat": "Face Makeup", "name": "Long-wear Setting Spray", "price": 879, "mrp": 1009, "rating": 4.7, "reviews": 946, "color": "#aebfb0", "img": ""},
  {"id": "b70", "section": "beauty", "cat": "Face Makeup", "name": "Contour Palette Duo", "price": 569, "mrp": 829, "rating": 4.3, "reviews": 1077, "color": "#f2c9a5", "img": ""},
  {"id": "b71", "section": "beauty", "cat": "Eye Makeup", "name": "Smudge-proof Kajal Black", "price": 149, "mrp": 169, "rating": 4.0, "reviews": 1261, "color": "#f2c9a5", "img": ""},
  {"id": "b72", "section": "beauty", "cat": "Eye Makeup", "name": "Volume Mascara", "price": 729, "mrp": 1059, "rating": 4.7, "reviews": 1392, "color": "#e9a0a8", "img": ""},
  {"id": "b73", "section": "beauty", "cat": "Eye Makeup", "name": "Waterproof Liquid Eyeliner", "price": 479, "mrp": 549, "rating": 4.3, "reviews": 1523, "color": "#cdb4c9", "img": ""},
  {"id": "b74", "section": "beauty", "cat": "Eye Makeup", "name": "Neutral Eyeshadow Palette", "price": 229, "mrp": 329, "rating": 3.9, "reviews": 1654, "color": "#b9c7e0", "img": ""},
  {"id": "b75", "section": "beauty", "cat": "Eye Makeup", "name": "Bold Eyeshadow Palette", "price": 819, "mrp": 939, "rating": 4.6, "reviews": 1785, "color": "#c9d6c3", "img": ""},
  {"id": "b76", "section": "beauty", "cat": "Eye Makeup", "name": "Brown Brow Pencil", "price": 569, "mrp": 829, "rating": 4.2, "reviews": 1916, "color": "#e3b66b", "img": ""},
  {"id": "b77", "section": "beauty", "cat": "Eye Makeup", "name": "Gel Eyeliner Pot", "price": 319, "mrp": 369, "rating": 3.8, "reviews": 2047, "color": "#d9a6a0", "img": ""},
  {"id": "b78", "section": "beauty", "cat": "Eye Makeup", "name": "Glitter Eye Pencil", "price": 899, "mrp": 1299, "rating": 4.5, "reviews": 2178, "color": "#c8cdd6", "img": ""},
  {"id": "b79", "section": "beauty", "cat": "Eye Makeup", "name": "Natural False Lashes", "price": 649, "mrp": 749, "rating": 4.1, "reviews": 2309, "color": "#d8b99a", "img": ""},
  {"id": "b80", "section": "beauty", "cat": "Eye Makeup", "name": "Eye Makeup Remover", "price": 399, "mrp": 579, "rating": 4.8, "reviews": 2440, "color": "#aebfb0", "img": ""},
  {"id": "b81", "section": "beauty", "cat": "Hair Care", "name": "Argan Hair Oil", "price": 199, "mrp": 229, "rating": 4.5, "reviews": 2624, "color": "#aebfb0", "img": ""},
  {"id": "b82", "section": "beauty", "cat": "Hair Care", "name": "Onion Hair Oil", "price": 819, "mrp": 1189, "rating": 4.1, "reviews": 2755, "color": "#f2c9a5", "img": ""},
  {"id": "b83", "section": "beauty", "cat": "Hair Care", "name": "Anti-Frizz Shampoo", "price": 549, "mrp": 629, "rating": 4.8, "reviews": 2886, "color": "#e9a0a8", "img": ""},
  {"id": "b84", "section": "beauty", "cat": "Hair Care", "name": "Keratin Conditioner", "price": 289, "mrp": 419, "rating": 4.4, "reviews": 217, "color": "#cdb4c9", "img": ""},
  {"id": "b85", "section": "beauty", "cat": "Hair Care", "name": "Deep Repair Hair Mask", "price": 909, "mrp": 1049, "rating": 4.0, "reviews": 348, "color": "#b9c7e0", "img": ""},
  {"id": "b86", "section": "beauty", "cat": "Hair Care", "name": "Leave-in Hair Serum", "price": 639, "mrp": 929, "rating": 4.7, "reviews": 479, "color": "#c9d6c3", "img": ""},
  {"id": "b87", "section": "beauty", "cat": "Hair Care", "name": "Heat Protect Spray", "price": 379, "mrp": 439, "rating": 4.3, "reviews": 610, "color": "#e3b66b", "img": ""},
  {"id": "b88", "section": "beauty", "cat": "Hair Care", "name": "Scalp Scrub", "price": 999, "mrp": 1449, "rating": 3.9, "reviews": 741, "color": "#d9a6a0", "img": ""},
  {"id": "b89", "section": "beauty", "cat": "Hair Care", "name": "Rosemary Hair Growth Oil", "price": 729, "mrp": 839, "rating": 4.6, "reviews": 872, "color": "#c8cdd6", "img": ""},
  {"id": "b90", "section": "beauty", "cat": "Hair Care", "name": "Dry Shampoo", "price": 469, "mrp": 679, "rating": 4.2, "reviews": 1003, "color": "#d8b99a", "img": ""},
  {"id": "b91", "section": "beauty", "cat": "Nails & Tools", "name": "Classic Red Nail Polish", "price": 99, "mrp": 109, "rating": 3.9, "reviews": 1187, "color": "#b9c7e0", "img": ""},
  {"id": "b92", "section": "beauty", "cat": "Nails & Tools", "name": "Nude Nail Polish Set of 3", "price": 1029, "mrp": 1489, "rating": 4.6, "reviews": 1318, "color": "#c9d6c3", "img": ""},
  {"id": "b93", "section": "beauty", "cat": "Nails & Tools", "name": "Gel-finish Top Coat", "price": 629, "mrp": 719, "rating": 4.2, "reviews": 1449, "color": "#e3b66b", "img": ""},
  {"id": "b94", "section": "beauty", "cat": "Nails & Tools", "name": "Nail Art Kit", "price": 229, "mrp": 329, "rating": 3.8, "reviews": 1580, "color": "#d9a6a0", "img": ""},
  {"id": "b95", "section": "beauty", "cat": "Nails & Tools", "name": "Nail Polish Remover", "price": 1169, "mrp": 1339, "rating": 4.5, "reviews": 1711, "color": "#c8cdd6", "img": ""},
  {"id": "b96", "section": "beauty", "cat": "Nails & Tools", "name": "Makeup Brush Set (10 pcs)", "price": 769, "mrp": 1119, "rating": 4.1, "reviews": 1842, "color": "#d8b99a", "img": ""},
  {"id": "b97", "section": "beauty", "cat": "Nails & Tools", "name": "Beauty Blender Sponge", "price": 369, "mrp": 419, "rating": 4.8, "reviews": 1973, "color": "#aebfb0", "img": ""},
  {"id": "b98", "section": "beauty", "cat": "Nails & Tools", "name": "Eyelash Curler", "price": 1299, "mrp": 1879, "rating": 4.4, "reviews": 2104, "color": "#f2c9a5", "img": ""},
  {"id": "b99", "section": "beauty", "cat": "Nails & Tools", "name": "Jade Face Roller", "price": 899, "mrp": 1029, "rating": 4.0, "reviews": 2235, "color": "#e9a0a8", "img": ""},
  {"id": "b100", "section": "beauty", "cat": "Nails & Tools", "name": "Makeup Organiser Box", "price": 499, "mrp": 719, "rating": 4.7, "reviews": 2366, "color": "#cdb4c9", "img": ""},
  {"id": "f1", "section": "fashion", "cat": "Kurta Sets", "name": "Cotton Straight Kurta Set", "price": 799, "mrp": 919, "rating": 3.8, "reviews": 120, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f2", "section": "fashion", "cat": "Kurta Sets", "name": "Chikankari Kurta Set", "price": 2509, "mrp": 3639, "rating": 4.5, "reviews": 251, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f3", "section": "fashion", "cat": "Kurta Sets", "name": "Anarkali Kurta Set", "price": 1779, "mrp": 2049, "rating": 4.1, "reviews": 382, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f4", "section": "fashion", "cat": "Kurta Sets", "name": "Sharara Set", "price": 1039, "mrp": 1509, "rating": 4.8, "reviews": 513, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f5", "section": "fashion", "cat": "Kurta Sets", "name": "Block Print Kurta with Palazzo", "price": 2749, "mrp": 3159, "rating": 4.4, "reviews": 644, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f6", "section": "fashion", "cat": "Kurta Sets", "name": "Short Kurti with Pants", "price": 2019, "mrp": 2929, "rating": 4.0, "reviews": 775, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f7", "section": "fashion", "cat": "Kurta Sets", "name": "Embroidered Festive Kurta Set", "price": 1289, "mrp": 1479, "rating": 4.7, "reviews": 906, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f8", "section": "fashion", "cat": "Kurta Sets", "name": "Linen Kurta Set", "price": 2999, "mrp": 4349, "rating": 4.3, "reviews": 1037, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f9", "section": "fashion", "cat": "Kurta Sets", "name": "Printed Kurta with Dupatta", "price": 2269, "mrp": 2609, "rating": 3.9, "reviews": 1168, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f10", "section": "fashion", "cat": "Kurta Sets", "name": "Mens Cotton Kurta Pyjama", "price": 1529, "mrp": 2219, "rating": 4.6, "reviews": 1299, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f11", "section": "fashion", "cat": "Sarees", "name": "Banarasi Silk Saree", "price": 999, "mrp": 1149, "rating": 4.3, "reviews": 1483, "color": "#d9a6a0", "img": ""},
  {"id": "f12", "section": "fashion", "cat": "Sarees", "name": "Kanjivaram Silk Saree", "price": 5669, "mrp": 8219, "rating": 3.9, "reviews": 1614, "color": "#c8cdd6", "img": ""},
  {"id": "f13", "section": "fashion", "cat": "Sarees", "name": "Pre-stitched Ready Saree", "price": 3669, "mrp": 4219, "rating": 4.6, "reviews": 1745, "color": "#d8b99a", "img": ""},
  {"id": "f14", "section": "fashion", "cat": "Sarees", "name": "Georgette Party Saree", "price": 1669, "mrp": 2419, "rating": 4.2, "reviews": 1876, "color": "#aebfb0", "img": ""},
  {"id": "f15", "section": "fashion", "cat": "Sarees", "name": "Cotton Handloom Saree", "price": 6329, "mrp": 7279, "rating": 3.8, "reviews": 2007, "color": "#f2c9a5", "img": ""},
  {"id": "f16", "section": "fashion", "cat": "Sarees", "name": "Organza Saree", "price": 4329, "mrp": 6279, "rating": 4.5, "reviews": 2138, "color": "#e9a0a8", "img": ""},
  {"id": "f17", "section": "fashion", "cat": "Sarees", "name": "Chiffon Floral Saree", "price": 2329, "mrp": 2679, "rating": 4.1, "reviews": 2269, "color": "#cdb4c9", "img": ""},
  {"id": "f18", "section": "fashion", "cat": "Sarees", "name": "Linen Saree", "price": 6999, "mrp": 10149, "rating": 4.8, "reviews": 2400, "color": "#b9c7e0", "img": ""},
  {"id": "f19", "section": "fashion", "cat": "Sarees", "name": "Satin Ruffle Saree", "price": 4999, "mrp": 5749, "rating": 4.4, "reviews": 2531, "color": "#c9d6c3", "img": ""},
  {"id": "f20", "section": "fashion", "cat": "Sarees", "name": "Bandhani Saree", "price": 2999, "mrp": 4349, "rating": 4.0, "reviews": 2662, "color": "#e3b66b", "img": ""},
  {"id": "f21", "section": "fashion", "cat": "Dresses", "name": "Floral Maxi Dress", "price": 799, "mrp": 919, "rating": 4.8, "reviews": 2846, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f22", "section": "fashion", "cat": "Dresses", "name": "Wrap Midi Dress", "price": 2899, "mrp": 4199, "rating": 4.4, "reviews": 177, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f23", "section": "fashion", "cat": "Dresses", "name": "Bodycon Party Dress", "price": 1999, "mrp": 2299, "rating": 4.0, "reviews": 308, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f24", "section": "fashion", "cat": "Dresses", "name": "Shirt Dress", "price": 1099, "mrp": 1589, "rating": 4.7, "reviews": 439, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f25", "section": "fashion", "cat": "Dresses", "name": "A-line Summer Dress", "price": 3199, "mrp": 3679, "rating": 4.3, "reviews": 570, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f26", "section": "fashion", "cat": "Dresses", "name": "Linen Co-ord Set", "price": 2299, "mrp": 3329, "rating": 3.9, "reviews": 701, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f27", "section": "fashion", "cat": "Dresses", "name": "Satin Slip Dress", "price": 1399, "mrp": 1609, "rating": 4.6, "reviews": 832, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f28", "section": "fashion", "cat": "Dresses", "name": "Tiered Boho Dress", "price": 3499, "mrp": 5069, "rating": 4.2, "reviews": 963, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f29", "section": "fashion", "cat": "Dresses", "name": "Little Black Dress", "price": 2599, "mrp": 2989, "rating": 3.8, "reviews": 1094, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f30", "section": "fashion", "cat": "Dresses", "name": "Indo-Western Gown", "price": 1699, "mrp": 2459, "rating": 4.5, "reviews": 1225, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f31", "section": "fashion", "cat": "Tops & T-shirts", "name": "Oversized T-shirt", "price": 299, "mrp": 339, "rating": 4.2, "reviews": 1409, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f32", "section": "fashion", "cat": "Tops & T-shirts", "name": "Graphic Tee", "price": 1229, "mrp": 1779, "rating": 3.8, "reviews": 1540, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f33", "section": "fashion", "cat": "Tops & T-shirts", "name": "Crop Top", "price": 829, "mrp": 949, "rating": 4.5, "reviews": 1671, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f34", "section": "fashion", "cat": "Tops & T-shirts", "name": "Ribbed Tank Top", "price": 429, "mrp": 619, "rating": 4.1, "reviews": 1802, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f35", "section": "fashion", "cat": "Tops & T-shirts", "name": "Linen Shirt", "price": 1369, "mrp": 1569, "rating": 4.8, "reviews": 1933, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f36", "section": "fashion", "cat": "Tops & T-shirts", "name": "Polo T-shirt", "price": 969, "mrp": 1409, "rating": 4.4, "reviews": 2064, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f37", "section": "fashion", "cat": "Tops & T-shirts", "name": "Peplum Top", "price": 569, "mrp": 649, "rating": 4.0, "reviews": 2195, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f38", "section": "fashion", "cat": "Tops & T-shirts", "name": "Puff Sleeve Blouse", "price": 1499, "mrp": 2169, "rating": 4.7, "reviews": 2326, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f39", "section": "fashion", "cat": "Tops & T-shirts", "name": "Basic White Tee", "price": 1099, "mrp": 1259, "rating": 4.3, "reviews": 2457, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f40", "section": "fashion", "cat": "Tops & T-shirts", "name": "Printed Casual Shirt", "price": 699, "mrp": 1009, "rating": 3.9, "reviews": 2588, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f41", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Premium Cotton Hoodie", "price": 799, "mrp": 919, "rating": 4.7, "reviews": 2772, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f42", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Zip-up Hoodie", "price": 3289, "mrp": 4769, "rating": 4.3, "reviews": 2903, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f43", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Denim Jacket", "price": 2219, "mrp": 2549, "rating": 3.9, "reviews": 234, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f44", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Bomber Jacket", "price": 1149, "mrp": 1669, "rating": 4.6, "reviews": 365, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f45", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Puffer Jacket", "price": 3639, "mrp": 4179, "rating": 4.2, "reviews": 496, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f46", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Knit Cardigan", "price": 2579, "mrp": 3739, "rating": 3.8, "reviews": 627, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f47", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Crewneck Sweatshirt", "price": 1509, "mrp": 1739, "rating": 4.5, "reviews": 758, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f48", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Windcheater", "price": 3999, "mrp": 5799, "rating": 4.1, "reviews": 889, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f49", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Women's Blazer", "price": 2929, "mrp": 3369, "rating": 4.8, "reviews": 1020, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f50", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Check Shacket", "price": 1869, "mrp": 2709, "rating": 4.4, "reviews": 1151, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f51", "section": "fashion", "cat": "Jeans & Pants", "name": "Baggy Jeans", "price": 599, "mrp": 689, "rating": 4.1, "reviews": 1335, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f52", "section": "fashion", "cat": "Jeans & Pants", "name": "Straight Fit Jeans", "price": 2079, "mrp": 3009, "rating": 4.8, "reviews": 1466, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f53", "section": "fashion", "cat": "Jeans & Pants", "name": "Cargo Pants", "price": 1439, "mrp": 1649, "rating": 4.4, "reviews": 1597, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f54", "section": "fashion", "cat": "Jeans & Pants", "name": "Joggers", "price": 809, "mrp": 1169, "rating": 4.0, "reviews": 1728, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f55", "section": "fashion", "cat": "Jeans & Pants", "name": "Palazzo Pants", "price": 2289, "mrp": 2629, "rating": 4.7, "reviews": 1859, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f56", "section": "fashion", "cat": "Jeans & Pants", "name": "Wide-leg Trousers", "price": 1649, "mrp": 2389, "rating": 4.3, "reviews": 1990, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f57", "section": "fashion", "cat": "Jeans & Pants", "name": "Mom Jeans", "price": 1019, "mrp": 1169, "rating": 3.9, "reviews": 2121, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f58", "section": "fashion", "cat": "Jeans & Pants", "name": "Linen Pants", "price": 2499, "mrp": 3619, "rating": 4.6, "reviews": 2252, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f59", "section": "fashion", "cat": "Jeans & Pants", "name": "Cotton Leggings", "price": 1869, "mrp": 2149, "rating": 4.2, "reviews": 2383, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f60", "section": "fashion", "cat": "Jeans & Pants", "name": "Culottes", "price": 1229, "mrp": 1779, "rating": 3.8, "reviews": 2514, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f61", "section": "fashion", "cat": "Jewellery", "name": "Oxidised Silver Jhumkas", "price": 199, "mrp": 229, "rating": 4.6, "reviews": 2698, "color": "#aebfb0", "img": ""},
  {"id": "f62", "section": "fashion", "cat": "Jewellery", "name": "Pearl Stud Earrings", "price": 1989, "mrp": 2879, "rating": 4.2, "reviews": 2829, "color": "#f2c9a5", "img": ""},
  {"id": "f63", "section": "fashion", "cat": "Jewellery", "name": "Layered Gold-tone Necklace", "price": 1219, "mrp": 1399, "rating": 3.8, "reviews": 160, "color": "#e9a0a8", "img": ""},
  {"id": "f64", "section": "fashion", "cat": "Jewellery", "name": "Silver Choker", "price": 449, "mrp": 649, "rating": 4.5, "reviews": 291, "color": "#cdb4c9", "img": ""},
  {"id": "f65", "section": "fashion", "cat": "Jewellery", "name": "Temple Jewellery Set", "price": 2239, "mrp": 2569, "rating": 4.1, "reviews": 422, "color": "#b9c7e0", "img": ""},
  {"id": "f66", "section": "fashion", "cat": "Jewellery", "name": "Kundan Earrings", "price": 1479, "mrp": 2139, "rating": 4.8, "reviews": 553, "color": "#c9d6c3", "img": ""},
  {"id": "f67", "section": "fashion", "cat": "Jewellery", "name": "Stackable Rings Set", "price": 709, "mrp": 819, "rating": 4.4, "reviews": 684, "color": "#e3b66b", "img": ""},
  {"id": "f68", "section": "fashion", "cat": "Jewellery", "name": "Charm Bracelet", "price": 2499, "mrp": 3619, "rating": 4.0, "reviews": 815, "color": "#d9a6a0", "img": ""},
  {"id": "f69", "section": "fashion", "cat": "Jewellery", "name": "Silver Anklet Pair", "price": 1729, "mrp": 1989, "rating": 4.7, "reviews": 946, "color": "#c8cdd6", "img": ""},
  {"id": "f70", "section": "fashion", "cat": "Jewellery", "name": "Nose Pin Studs", "price": 969, "mrp": 1409, "rating": 4.3, "reviews": 1077, "color": "#d8b99a", "img": ""},
  {"id": "f71", "section": "fashion", "cat": "Handbags", "name": "Everyday Tote Bag", "price": 499, "mrp": 569, "rating": 4.0, "reviews": 1261, "color": "#d8b99a", "img": ""},
  {"id": "f72", "section": "fashion", "cat": "Handbags", "name": "Sling Bag", "price": 2439, "mrp": 3539, "rating": 4.7, "reviews": 1392, "color": "#aebfb0", "img": ""},
  {"id": "f73", "section": "fashion", "cat": "Handbags", "name": "Mini Crossbody Bag", "price": 1609, "mrp": 1849, "rating": 4.3, "reviews": 1523, "color": "#f2c9a5", "img": ""},
  {"id": "f74", "section": "fashion", "cat": "Handbags", "name": "Casual Backpack", "price": 779, "mrp": 1129, "rating": 3.9, "reviews": 1654, "color": "#e9a0a8", "img": ""},
  {"id": "f75", "section": "fashion", "cat": "Handbags", "name": "Party Clutch", "price": 2719, "mrp": 3129, "rating": 4.6, "reviews": 1785, "color": "#cdb4c9", "img": ""},
  {"id": "f76", "section": "fashion", "cat": "Handbags", "name": "Embroidered Potli Bag", "price": 1889, "mrp": 2739, "rating": 4.2, "reviews": 1916, "color": "#b9c7e0", "img": ""},
  {"id": "f77", "section": "fashion", "cat": "Handbags", "name": "Laptop Bag", "price": 1049, "mrp": 1209, "rating": 3.8, "reviews": 2047, "color": "#c9d6c3", "img": ""},
  {"id": "f78", "section": "fashion", "cat": "Handbags", "name": "Canvas Tote", "price": 2999, "mrp": 4349, "rating": 4.5, "reviews": 2178, "color": "#e3b66b", "img": ""},
  {"id": "f79", "section": "fashion", "cat": "Handbags", "name": "Women's Wallet", "price": 2169, "mrp": 2489, "rating": 4.1, "reviews": 2309, "color": "#d9a6a0", "img": ""},
  {"id": "f80", "section": "fashion", "cat": "Handbags", "name": "Travel Duffle Bag", "price": 1329, "mrp": 1929, "rating": 4.8, "reviews": 2440, "color": "#c8cdd6", "img": ""},
  {"id": "f81", "section": "fashion", "cat": "Footwear", "name": "White Sneakers", "price": 499, "mrp": 569, "rating": 4.5, "reviews": 2624, "color": "#d8b99a", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f82", "section": "fashion", "cat": "Footwear", "name": "Kolhapuri Chappals", "price": 2829, "mrp": 4099, "rating": 4.1, "reviews": 2755, "color": "#aebfb0", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f83", "section": "fashion", "cat": "Footwear", "name": "Block Heels", "price": 1829, "mrp": 2099, "rating": 4.8, "reviews": 2886, "color": "#f2c9a5", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f84", "section": "fashion", "cat": "Footwear", "name": "Ballet Flats", "price": 829, "mrp": 1199, "rating": 4.4, "reviews": 217, "color": "#e9a0a8", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f85", "section": "fashion", "cat": "Footwear", "name": "Running Shoes", "price": 3169, "mrp": 3639, "rating": 4.0, "reviews": 348, "color": "#cdb4c9", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f86", "section": "fashion", "cat": "Footwear", "name": "Strappy Sandals", "price": 2169, "mrp": 3149, "rating": 4.7, "reviews": 479, "color": "#b9c7e0", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f87", "section": "fashion", "cat": "Footwear", "name": "Embroidered Juttis", "price": 1169, "mrp": 1339, "rating": 4.3, "reviews": 610, "color": "#c9d6c3", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f88", "section": "fashion", "cat": "Footwear", "name": "Soft Sliders", "price": 3499, "mrp": 5069, "rating": 3.9, "reviews": 741, "color": "#e3b66b", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f89", "section": "fashion", "cat": "Footwear", "name": "Loafers", "price": 2499, "mrp": 2869, "rating": 4.6, "reviews": 872, "color": "#d9a6a0", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f90", "section": "fashion", "cat": "Footwear", "name": "Ankle Boots", "price": 1499, "mrp": 2169, "rating": 4.2, "reviews": 1003, "color": "#c8cdd6", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f91", "section": "fashion", "cat": "Activewear", "name": "Gym Leggings", "price": 299, "mrp": 339, "rating": 3.9, "reviews": 1187, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f92", "section": "fashion", "cat": "Activewear", "name": "Sports Bra", "price": 2009, "mrp": 2909, "rating": 4.6, "reviews": 1318, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f93", "section": "fashion", "cat": "Activewear", "name": "Training T-shirt", "price": 1279, "mrp": 1469, "rating": 4.2, "reviews": 1449, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f94", "section": "fashion", "cat": "Activewear", "name": "Track Pants", "price": 539, "mrp": 779, "rating": 3.8, "reviews": 1580, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f95", "section": "fashion", "cat": "Activewear", "name": "Yoga Mat", "price": 2249, "mrp": 2589, "rating": 4.5, "reviews": 1711, "color": "#c9d6c3", "img": ""},
  {"id": "f96", "section": "fashion", "cat": "Activewear", "name": "Compression Shorts", "price": 1519, "mrp": 2199, "rating": 4.1, "reviews": 1842, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f97", "section": "fashion", "cat": "Activewear", "name": "Running Jacket", "price": 789, "mrp": 909, "rating": 4.8, "reviews": 1973, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f98", "section": "fashion", "cat": "Activewear", "name": "Gym Duffel Bag", "price": 2499, "mrp": 3619, "rating": 4.4, "reviews": 2104, "color": "#c8cdd6", "img": ""},
  {"id": "f99", "section": "fashion", "cat": "Activewear", "name": "Sports Socks (3 pack)", "price": 1769, "mrp": 2029, "rating": 4.0, "reviews": 2235, "color": "#d8b99a", "img": ""},
  {"id": "f100", "section": "fashion", "cat": "Activewear", "name": "Two-piece Active Set", "price": 1029, "mrp": 1489, "rating": 4.7, "reviews": 2366, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}}
];

// ===== 10 more products in every category (20 per category) =====
allProducts.push(
  {"id": "b101", "section": "beauty", "cat": "Sunscreen", "name": "Vitamin E Sunscreen Lotion SPF 40", "price": 289, "mrp": 369, "rating": 4, "reviews": 2045, "color": "#f2c9a5", "img": ""},
  {"id": "b102", "section": "beauty", "cat": "Sunscreen", "name": "Zinc Oxide Mineral Sunscreen SPF 30", "price": 429, "mrp": 519, "rating": 4.8, "reviews": 4174, "color": "#e9a0a8", "img": ""},
  {"id": "b103", "section": "beauty", "cat": "Sunscreen", "name": "Watery Essence Sunscreen SPF 50", "price": 889, "mrp": 1149, "rating": 4.2, "reviews": 1097, "color": "#cdb4c9", "img": ""},
  {"id": "b104", "section": "beauty", "cat": "Sunscreen", "name": "Sun Protect Cushion Compact SPF 35", "price": 369, "mrp": 439, "rating": 3.9, "reviews": 377, "color": "#b9c7e0", "img": ""},
  {"id": "b105", "section": "beauty", "cat": "Sunscreen", "name": "Rose Glow Sunscreen Cream SPF 40", "price": 759, "mrp": 1069, "rating": 4.6, "reviews": 2701, "color": "#c9d6c3", "img": ""},
  {"id": "b106", "section": "beauty", "cat": "Sunscreen", "name": "Sweatproof Sports Sunscreen SPF 50", "price": 349, "mrp": 399, "rating": 4.7, "reviews": 3007, "color": "#e3b66b", "img": ""},
  {"id": "b107", "section": "beauty", "cat": "Sunscreen", "name": "Ultra Light Sunscreen Serum SPF 45", "price": 749, "mrp": 999, "rating": 4.1, "reviews": 3104, "color": "#d9a6a0", "img": ""},
  {"id": "b108", "section": "beauty", "cat": "Sunscreen", "name": "Niacinamide Brightening Sunscreen", "price": 789, "mrp": 1159, "rating": 4.2, "reviews": 3917, "color": "#c8cdd6", "img": ""},
  {"id": "b109", "section": "beauty", "cat": "Sunscreen", "name": "Sunscreen Lip Balm SPF 30", "price": 479, "mrp": 749, "rating": 4.2, "reviews": 764, "color": "#d8b99a", "img": ""},
  {"id": "b110", "section": "beauty", "cat": "Sunscreen", "name": "Body Sunscreen Lotion SPF 50", "price": 769, "mrp": 1149, "rating": 3.9, "reviews": 4104, "color": "#aebfb0", "img": ""},
  {"id": "b111", "section": "beauty", "cat": "Lipstick", "name": "Satin Mauve Lipstick", "price": 939, "mrp": 1099, "rating": 4.6, "reviews": 2055, "color": "#f2c9a5", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b112", "section": "beauty", "cat": "Lipstick", "name": "Velvet Pink Lip Cream", "price": 629, "mrp": 949, "rating": 4, "reviews": 1381, "color": "#e9a0a8", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b113", "section": "beauty", "cat": "Lipstick", "name": "Glossy Plumping Lip Oil", "price": 639, "mrp": 1029, "rating": 4.6, "reviews": 1475, "color": "#cdb4c9", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b114", "section": "beauty", "cat": "Lipstick", "name": "Hydrating Lip Tint Duo", "price": 689, "mrp": 859, "rating": 4.3, "reviews": 2354, "color": "#b9c7e0", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b115", "section": "beauty", "cat": "Lipstick", "name": "Terracotta Matte Lipstick", "price": 829, "mrp": 1149, "rating": 4.6, "reviews": 1520, "color": "#c9d6c3", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b116", "section": "beauty", "cat": "Lipstick", "name": "Orange Pop Lipstick", "price": 639, "mrp": 699, "rating": 4.7, "reviews": 4447, "color": "#e3b66b", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b117", "section": "beauty", "cat": "Lipstick", "name": "Everyday Nude Lip Liner", "price": 949, "mrp": 1559, "rating": 4.6, "reviews": 3276, "color": "#d9a6a0", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b118", "section": "beauty", "cat": "Lipstick", "name": "Shimmer Gold Lip Gloss", "price": 959, "mrp": 1369, "rating": 3.9, "reviews": 4584, "color": "#c8cdd6", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b119", "section": "beauty", "cat": "Lipstick", "name": "Mini Lipstick Set of 4", "price": 449, "mrp": 669, "rating": 4.1, "reviews": 1368, "color": "#d8b99a", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b120", "section": "beauty", "cat": "Lipstick", "name": "Two-tone Lip & Cheek Stick", "price": 689, "mrp": 1149, "rating": 4.6, "reviews": 1713, "color": "#aebfb0", "img": "", "opts": {"label": "Shade", "values": ["Rose", "Nude", "Berry", "Red"]}},
  {"id": "b121", "section": "beauty", "cat": "Perfume", "name": "Musk Rose Eau de Parfum", "price": 1179, "mrp": 1549, "rating": 4.2, "reviews": 312, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b122", "section": "beauty", "cat": "Perfume", "name": "Fresh Linen Body Mist", "price": 679, "mrp": 999, "rating": 3.9, "reviews": 1043, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b123", "section": "beauty", "cat": "Perfume", "name": "Midnight Oud Attar", "price": 869, "mrp": 1339, "rating": 4.4, "reviews": 3733, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b124", "section": "beauty", "cat": "Perfume", "name": "Green Tea Cologne", "price": 1629, "mrp": 1889, "rating": 4.5, "reviews": 2594, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b125", "section": "beauty", "cat": "Perfume", "name": "Cherry Blossom Eau de Toilette", "price": 1479, "mrp": 2109, "rating": 3.9, "reviews": 1625, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b126", "section": "beauty", "cat": "Perfume", "name": "Coconut Vanilla Body Mist", "price": 1429, "mrp": 1589, "rating": 4.6, "reviews": 1197, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b127", "section": "beauty", "cat": "Perfume", "name": "Cedar & Amber Perfume", "price": 2149, "mrp": 2899, "rating": 4.6, "reviews": 1560, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b128", "section": "beauty", "cat": "Perfume", "name": "Gardenia Roll-on Perfume", "price": 1179, "mrp": 1319, "rating": 4.2, "reviews": 4527, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b129", "section": "beauty", "cat": "Perfume", "name": "Travel Perfume Trio", "price": 1319, "mrp": 1589, "rating": 4, "reviews": 1275, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b130", "section": "beauty", "cat": "Perfume", "name": "Sparkling Pear Eau de Parfum", "price": 1809, "mrp": 2209, "rating": 4, "reviews": 4369, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["30 ml", "50 ml", "100 ml"]}},
  {"id": "b131", "section": "beauty", "cat": "Face Serum", "name": "Kojic Acid Brightening Serum", "price": 1319, "mrp": 2199, "rating": 4.5, "reviews": 4778, "color": "#f2c9a5", "img": ""},
  {"id": "b132", "section": "beauty", "cat": "Face Serum", "name": "Bakuchiol Night Serum", "price": 389, "mrp": 519, "rating": 4.3, "reviews": 1557, "color": "#e9a0a8", "img": ""},
  {"id": "b133", "section": "beauty", "cat": "Face Serum", "name": "Hydra Gel Water Serum", "price": 1259, "mrp": 1449, "rating": 4.6, "reviews": 2877, "color": "#cdb4c9", "img": ""},
  {"id": "b134", "section": "beauty", "cat": "Face Serum", "name": "Tranexamic Acid Serum", "price": 589, "mrp": 689, "rating": 4.8, "reviews": 276, "color": "#b9c7e0", "img": ""},
  {"id": "b135", "section": "beauty", "cat": "Face Serum", "name": "Vitamin E Glow Serum", "price": 1039, "mrp": 1219, "rating": 4.1, "reviews": 695, "color": "#c9d6c3", "img": ""},
  {"id": "b136", "section": "beauty", "cat": "Face Serum", "name": "Centella Soothing Serum", "price": 1319, "mrp": 1479, "rating": 3.9, "reviews": 857, "color": "#e3b66b", "img": ""},
  {"id": "b137", "section": "beauty", "cat": "Face Serum", "name": "Collagen Boost Serum", "price": 909, "mrp": 1229, "rating": 4.4, "reviews": 849, "color": "#d9a6a0", "img": ""},
  {"id": "b138", "section": "beauty", "cat": "Face Serum", "name": "Rosehip Face Oil", "price": 1429, "mrp": 2009, "rating": 3.9, "reviews": 2111, "color": "#c8cdd6", "img": ""},
  {"id": "b139", "section": "beauty", "cat": "Face Serum", "name": "Lactic Acid Smoothing Serum", "price": 589, "mrp": 839, "rating": 4.6, "reviews": 3614, "color": "#d8b99a", "img": ""},
  {"id": "b140", "section": "beauty", "cat": "Face Serum", "name": "Eyelash & Brow Growth Serum", "price": 1469, "mrp": 1859, "rating": 4.1, "reviews": 2639, "color": "#aebfb0", "img": ""},
  {"id": "b141", "section": "beauty", "cat": "Moisturizer", "name": "Hyaluronic Water Cream", "price": 409, "mrp": 669, "rating": 4.3, "reviews": 3515, "color": "#f2c9a5", "img": ""},
  {"id": "b142", "section": "beauty", "cat": "Moisturizer", "name": "Vitamin E Day Lotion", "price": 399, "mrp": 629, "rating": 4.2, "reviews": 3585, "color": "#e9a0a8", "img": ""},
  {"id": "b143", "section": "beauty", "cat": "Moisturizer", "name": "Oatmeal Sensitive Skin Cream", "price": 959, "mrp": 1199, "rating": 4.1, "reviews": 1875, "color": "#cdb4c9", "img": ""},
  {"id": "b144", "section": "beauty", "cat": "Moisturizer", "name": "Rice Water Gel Cream", "price": 849, "mrp": 1159, "rating": 4.7, "reviews": 4210, "color": "#b9c7e0", "img": ""},
  {"id": "b145", "section": "beauty", "cat": "Moisturizer", "name": "Squalane Face Moisturiser", "price": 1099, "mrp": 1639, "rating": 4.4, "reviews": 4438, "color": "#c9d6c3", "img": ""},
  {"id": "b146", "section": "beauty", "cat": "Moisturizer", "name": "Tinted Moisturiser SPF 25", "price": 329, "mrp": 419, "rating": 4.1, "reviews": 1078, "color": "#e3b66b", "img": ""},
  {"id": "b147", "section": "beauty", "cat": "Moisturizer", "name": "Cooling Cucumber Gel", "price": 799, "mrp": 889, "rating": 4.1, "reviews": 2902, "color": "#d9a6a0", "img": ""},
  {"id": "b148", "section": "beauty", "cat": "Moisturizer", "name": "Honey Glow Body Lotion", "price": 319, "mrp": 369, "rating": 4.8, "reviews": 2264, "color": "#c8cdd6", "img": ""},
  {"id": "b149", "section": "beauty", "cat": "Moisturizer", "name": "Foot Repair Cream", "price": 689, "mrp": 849, "rating": 4.7, "reviews": 1376, "color": "#d8b99a", "img": ""},
  {"id": "b150", "section": "beauty", "cat": "Moisturizer", "name": "Overnight Sleeping Mask", "price": 379, "mrp": 459, "rating": 4.6, "reviews": 4244, "color": "#aebfb0", "img": ""},
  {"id": "b151", "section": "beauty", "cat": "Face Wash", "name": "Tea Tree Face Wash", "price": 209, "mrp": 259, "rating": 4.3, "reviews": 351, "color": "#f2c9a5", "img": ""},
  {"id": "b152", "section": "beauty", "cat": "Face Wash", "name": "Rose Water Gentle Cleanser", "price": 619, "mrp": 709, "rating": 4.7, "reviews": 3558, "color": "#e9a0a8", "img": ""},
  {"id": "b153", "section": "beauty", "cat": "Face Wash", "name": "Papaya Brightening Face Wash", "price": 389, "mrp": 469, "rating": 4, "reviews": 2779, "color": "#cdb4c9", "img": ""},
  {"id": "b154", "section": "beauty", "cat": "Face Wash", "name": "Honey Milk Cleanser", "price": 479, "mrp": 539, "rating": 3.9, "reviews": 3455, "color": "#b9c7e0", "img": ""},
  {"id": "b155", "section": "beauty", "cat": "Face Wash", "name": "Coffee Face Scrub", "price": 149, "mrp": 169, "rating": 4.4, "reviews": 2023, "color": "#c9d6c3", "img": ""},
  {"id": "b156", "section": "beauty", "cat": "Face Wash", "name": "Aloe Vera Face Wash", "price": 269, "mrp": 429, "rating": 3.8, "reviews": 2462, "color": "#e3b66b", "img": ""},
  {"id": "b157", "section": "beauty", "cat": "Face Wash", "name": "Oil Cleanser Makeup Melt", "price": 289, "mrp": 439, "rating": 3.9, "reviews": 3597, "color": "#d9a6a0", "img": ""},
  {"id": "b158", "section": "beauty", "cat": "Face Wash", "name": "Multani Mitti Face Pack", "price": 399, "mrp": 649, "rating": 4.3, "reviews": 1326, "color": "#c8cdd6", "img": ""},
  {"id": "b159", "section": "beauty", "cat": "Face Wash", "name": "Hydrating Cream Cleanser", "price": 289, "mrp": 339, "rating": 4.7, "reviews": 3706, "color": "#d8b99a", "img": ""},
  {"id": "b160", "section": "beauty", "cat": "Face Wash", "name": "Peel-off Charcoal Mask", "price": 519, "mrp": 579, "rating": 4.7, "reviews": 1351, "color": "#aebfb0", "img": ""},
  {"id": "b161", "section": "beauty", "cat": "Face Makeup", "name": "Cream Blush Stick", "price": 1009, "mrp": 1109, "rating": 4.4, "reviews": 4011, "color": "#f2c9a5", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b162", "section": "beauty", "cat": "Face Makeup", "name": "BB Cream SPF 20", "price": 469, "mrp": 599, "rating": 4.2, "reviews": 2409, "color": "#e9a0a8", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b163", "section": "beauty", "cat": "Face Makeup", "name": "Liquid Highlighter Drops", "price": 919, "mrp": 1279, "rating": 3.9, "reviews": 1806, "color": "#cdb4c9", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b164", "section": "beauty", "cat": "Face Makeup", "name": "Colour Correcting Concealer Palette", "price": 619, "mrp": 739, "rating": 4.3, "reviews": 4502, "color": "#b9c7e0", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b165", "section": "beauty", "cat": "Face Makeup", "name": "Dewy Skin Tint Foundation", "price": 1299, "mrp": 2129, "rating": 4.2, "reviews": 3608, "color": "#c9d6c3", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b166", "section": "beauty", "cat": "Face Makeup", "name": "Sun Kiss Bronzer", "price": 409, "mrp": 459, "rating": 3.8, "reviews": 3178, "color": "#e3b66b", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b167", "section": "beauty", "cat": "Face Makeup", "name": "Matte Finish Face Primer", "price": 929, "mrp": 1429, "rating": 4, "reviews": 4157, "color": "#d9a6a0", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b168", "section": "beauty", "cat": "Face Makeup", "name": "Cream Contour Stick", "price": 1219, "mrp": 1519, "rating": 4.2, "reviews": 4017, "color": "#c8cdd6", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b169", "section": "beauty", "cat": "Face Makeup", "name": "Cheek & Lip Tint Pot", "price": 939, "mrp": 1399, "rating": 4.4, "reviews": 3203, "color": "#d8b99a", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b170", "section": "beauty", "cat": "Face Makeup", "name": "Oil Blotting Paper (100 sheets)", "price": 789, "mrp": 1099, "rating": 4.4, "reviews": 3246, "color": "#aebfb0", "img": "", "opts": {"label": "Shade", "values": ["Fair", "Medium", "Deep"]}},
  {"id": "b171", "section": "beauty", "cat": "Eye Makeup", "name": "Liquid Kajal Pen", "price": 719, "mrp": 799, "rating": 4.8, "reviews": 3222, "color": "#f2c9a5", "img": ""},
  {"id": "b172", "section": "beauty", "cat": "Eye Makeup", "name": "Lengthening Mascara", "price": 499, "mrp": 799, "rating": 4.3, "reviews": 2495, "color": "#e9a0a8", "img": ""},
  {"id": "b173", "section": "beauty", "cat": "Eye Makeup", "name": "Brown Eyeliner Pencil", "price": 889, "mrp": 1019, "rating": 4, "reviews": 716, "color": "#cdb4c9", "img": ""},
  {"id": "b174", "section": "beauty", "cat": "Eye Makeup", "name": "Shimmer Eyeshadow Stick", "price": 639, "mrp": 929, "rating": 3.9, "reviews": 3597, "color": "#b9c7e0", "img": ""},
  {"id": "b175", "section": "beauty", "cat": "Eye Makeup", "name": "Pastel Eyeshadow Palette", "price": 579, "mrp": 829, "rating": 3.8, "reviews": 412, "color": "#c9d6c3", "img": ""},
  {"id": "b176", "section": "beauty", "cat": "Eye Makeup", "name": "Clear Brow Gel", "price": 899, "mrp": 1339, "rating": 3.9, "reviews": 499, "color": "#e3b66b", "img": ""},
  {"id": "b177", "section": "beauty", "cat": "Eye Makeup", "name": "Eyebrow Powder Kit", "price": 239, "mrp": 379, "rating": 4.3, "reviews": 3104, "color": "#d9a6a0", "img": ""},
  {"id": "b178", "section": "beauty", "cat": "Eye Makeup", "name": "Dramatic Volume Lashes", "price": 809, "mrp": 969, "rating": 3.9, "reviews": 621, "color": "#c8cdd6", "img": ""},
  {"id": "b179", "section": "beauty", "cat": "Eye Makeup", "name": "Eyeshadow Primer", "price": 159, "mrp": 179, "rating": 4.4, "reviews": 1324, "color": "#d8b99a", "img": ""},
  {"id": "b180", "section": "beauty", "cat": "Eye Makeup", "name": "Under-Eye Brightening Concealer", "price": 269, "mrp": 439, "rating": 4.5, "reviews": 4455, "color": "#aebfb0", "img": ""},
  {"id": "b181", "section": "beauty", "cat": "Hair Care", "name": "Coconut Hair Oil", "price": 939, "mrp": 1419, "rating": 4.7, "reviews": 2546, "color": "#f2c9a5", "img": ""},
  {"id": "b182", "section": "beauty", "cat": "Hair Care", "name": "Bhringraj Hair Oil", "price": 539, "mrp": 749, "rating": 4.2, "reviews": 3341, "color": "#e9a0a8", "img": ""},
  {"id": "b183", "section": "beauty", "cat": "Hair Care", "name": "Sulphate-free Shampoo", "price": 309, "mrp": 359, "rating": 3.9, "reviews": 4497, "color": "#cdb4c9", "img": ""},
  {"id": "b184", "section": "beauty", "cat": "Hair Care", "name": "Smoothing Conditioner", "price": 539, "mrp": 789, "rating": 3.8, "reviews": 2250, "color": "#b9c7e0", "img": ""},
  {"id": "b185", "section": "beauty", "cat": "Hair Care", "name": "Hair Growth Serum", "price": 539, "mrp": 799, "rating": 4.8, "reviews": 2319, "color": "#c9d6c3", "img": ""},
  {"id": "b186", "section": "beauty", "cat": "Hair Care", "name": "Curl Defining Cream", "price": 449, "mrp": 619, "rating": 4.5, "reviews": 896, "color": "#e3b66b", "img": ""},
  {"id": "b187", "section": "beauty", "cat": "Hair Care", "name": "Biotin Hair Mask", "price": 939, "mrp": 1399, "rating": 3.8, "reviews": 3446, "color": "#d9a6a0", "img": ""},
  {"id": "b188", "section": "beauty", "cat": "Hair Care", "name": "Wooden Detangling Comb", "price": 749, "mrp": 1129, "rating": 4, "reviews": 1525, "color": "#c8cdd6", "img": ""},
  {"id": "b189", "section": "beauty", "cat": "Hair Care", "name": "Silk Scrunchie Set", "price": 649, "mrp": 939, "rating": 4.4, "reviews": 3927, "color": "#d8b99a", "img": ""},
  {"id": "b190", "section": "beauty", "cat": "Hair Care", "name": "Anti-Dandruff Shampoo", "price": 649, "mrp": 969, "rating": 4.4, "reviews": 4728, "color": "#aebfb0", "img": ""},
  {"id": "b191", "section": "beauty", "cat": "Nails & Tools", "name": "Pastel Nail Polish Set of 5", "price": 909, "mrp": 1059, "rating": 3.9, "reviews": 3268, "color": "#f2c9a5", "img": ""},
  {"id": "b192", "section": "beauty", "cat": "Nails & Tools", "name": "Glitter Nail Polish", "price": 309, "mrp": 439, "rating": 4.2, "reviews": 1085, "color": "#e9a0a8", "img": ""},
  {"id": "b193", "section": "beauty", "cat": "Nails & Tools", "name": "Quick-dry Top Coat", "price": 539, "mrp": 629, "rating": 3.8, "reviews": 2906, "color": "#cdb4c9", "img": ""},
  {"id": "b194", "section": "beauty", "cat": "Nails & Tools", "name": "Nail Cuticle Oil", "price": 929, "mrp": 1429, "rating": 4.7, "reviews": 303, "color": "#b9c7e0", "img": ""},
  {"id": "b195", "section": "beauty", "cat": "Nails & Tools", "name": "Nail File & Buffer Set", "price": 859, "mrp": 1429, "rating": 4.4, "reviews": 3425, "color": "#c9d6c3", "img": ""},
  {"id": "b196", "section": "beauty", "cat": "Nails & Tools", "name": "Stick-on Nails Set", "price": 519, "mrp": 659, "rating": 4.5, "reviews": 4159, "color": "#e3b66b", "img": ""},
  {"id": "b197", "section": "beauty", "cat": "Nails & Tools", "name": "Makeup Sponge Set", "price": 119, "mrp": 179, "rating": 4.4, "reviews": 4273, "color": "#d9a6a0", "img": ""},
  {"id": "b198", "section": "beauty", "cat": "Nails & Tools", "name": "Concealer Brush", "price": 179, "mrp": 239, "rating": 4.8, "reviews": 837, "color": "#c8cdd6", "img": ""},
  {"id": "b199", "section": "beauty", "cat": "Nails & Tools", "name": "Powder Brush", "price": 139, "mrp": 219, "rating": 4, "reviews": 4037, "color": "#d8b99a", "img": ""},
  {"id": "b200", "section": "beauty", "cat": "Nails & Tools", "name": "Eyebrow Razor Set (3 pcs)", "price": 799, "mrp": 889, "rating": 3.9, "reviews": 2633, "color": "#aebfb0", "img": ""},
  {"id": "f101", "section": "fashion", "cat": "Kurta Sets", "name": "Rayon Anarkali Set", "price": 1759, "mrp": 2019, "rating": 3.8, "reviews": 693, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f102", "section": "fashion", "cat": "Kurta Sets", "name": "Pastel Chanderi Kurta Set", "price": 2629, "mrp": 3759, "rating": 4.7, "reviews": 4092, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f103", "section": "fashion", "cat": "Kurta Sets", "name": "Kalamkari Print Kurta Set", "price": 2949, "mrp": 3309, "rating": 3.9, "reviews": 1299, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f104", "section": "fashion", "cat": "Kurta Sets", "name": "Mirror Work Kurta Set", "price": 2369, "mrp": 3949, "rating": 3.9, "reviews": 4245, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f105", "section": "fashion", "cat": "Kurta Sets", "name": "Georgette Palazzo Set", "price": 2099, "mrp": 2589, "rating": 4.6, "reviews": 1388, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f106", "section": "fashion", "cat": "Kurta Sets", "name": "A-line Kurta with Pants", "price": 1979, "mrp": 2269, "rating": 4, "reviews": 3809, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f107", "section": "fashion", "cat": "Kurta Sets", "name": "Gota Patti Festive Set", "price": 2469, "mrp": 2869, "rating": 4.6, "reviews": 966, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f108", "section": "fashion", "cat": "Kurta Sets", "name": "Straight Cotton Kurti", "price": 2789, "mrp": 3869, "rating": 4.2, "reviews": 1806, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f109", "section": "fashion", "cat": "Kurta Sets", "name": "Bandhani Print Kurta Set", "price": 2529, "mrp": 2869, "rating": 3.9, "reviews": 2775, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f110", "section": "fashion", "cat": "Kurta Sets", "name": "Mens Silk Blend Kurta", "price": 2119, "mrp": 2619, "rating": 4.2, "reviews": 2866, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f111", "section": "fashion", "cat": "Sarees", "name": "Tussar Silk Saree", "price": 2179, "mrp": 2979, "rating": 4.7, "reviews": 772, "color": "#f2c9a5", "img": ""},
  {"id": "f112", "section": "fashion", "cat": "Sarees", "name": "Paithani Saree", "price": 5619, "mrp": 8029, "rating": 4.3, "reviews": 3816, "color": "#e9a0a8", "img": ""},
  {"id": "f113", "section": "fashion", "cat": "Sarees", "name": "Mysore Silk Saree", "price": 4059, "mrp": 5969, "rating": 4.4, "reviews": 1374, "color": "#cdb4c9", "img": ""},
  {"id": "f114", "section": "fashion", "cat": "Sarees", "name": "Net Embroidered Saree", "price": 5059, "mrp": 5749, "rating": 4.2, "reviews": 4531, "color": "#b9c7e0", "img": ""},
  {"id": "f115", "section": "fashion", "cat": "Sarees", "name": "Block Print Cotton Saree", "price": 999, "mrp": 1669, "rating": 4.3, "reviews": 4505, "color": "#c9d6c3", "img": ""},
  {"id": "f116", "section": "fashion", "cat": "Sarees", "name": "Sequin Party Saree", "price": 3989, "mrp": 4479, "rating": 3.9, "reviews": 1697, "color": "#e3b66b", "img": ""},
  {"id": "f117", "section": "fashion", "cat": "Sarees", "name": "Jamdani Saree", "price": 3719, "mrp": 4479, "rating": 4.3, "reviews": 3209, "color": "#d9a6a0", "img": ""},
  {"id": "f118", "section": "fashion", "cat": "Sarees", "name": "Kota Doria Saree", "price": 1649, "mrp": 2059, "rating": 4.8, "reviews": 2327, "color": "#c8cdd6", "img": ""},
  {"id": "f119", "section": "fashion", "cat": "Sarees", "name": "Patola Print Saree", "price": 3009, "mrp": 4069, "rating": 4.5, "reviews": 2543, "color": "#d8b99a", "img": ""},
  {"id": "f120", "section": "fashion", "cat": "Sarees", "name": "Ready-to-wear Lehenga Saree", "price": 3999, "mrp": 4649, "rating": 4.7, "reviews": 385, "color": "#aebfb0", "img": ""},
  {"id": "f121", "section": "fashion", "cat": "Dresses", "name": "Polka Dot Midi Dress", "price": 2939, "mrp": 3819, "rating": 4.8, "reviews": 951, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f122", "section": "fashion", "cat": "Dresses", "name": "Smocked Mini Dress", "price": 1249, "mrp": 1779, "rating": 3.8, "reviews": 4724, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f123", "section": "fashion", "cat": "Dresses", "name": "Off-shoulder Maxi Dress", "price": 1199, "mrp": 1559, "rating": 3.8, "reviews": 3791, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f124", "section": "fashion", "cat": "Dresses", "name": "Pleated Shirt Dress", "price": 1279, "mrp": 1469, "rating": 3.8, "reviews": 3688, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f125", "section": "fashion", "cat": "Dresses", "name": "Tie-dye Summer Dress", "price": 2839, "mrp": 3939, "rating": 4.5, "reviews": 1321, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f126", "section": "fashion", "cat": "Dresses", "name": "Velvet Evening Dress", "price": 1689, "mrp": 1989, "rating": 4.1, "reviews": 1968, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f127", "section": "fashion", "cat": "Dresses", "name": "Ruffle Wrap Dress", "price": 2449, "mrp": 2919, "rating": 3.9, "reviews": 3097, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f128", "section": "fashion", "cat": "Dresses", "name": "Denim Pinafore Dress", "price": 3239, "mrp": 5309, "rating": 3.9, "reviews": 1501, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f129", "section": "fashion", "cat": "Dresses", "name": "Halter Neck Dress", "price": 919, "mrp": 1459, "rating": 3.8, "reviews": 2699, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f130", "section": "fashion", "cat": "Dresses", "name": "Kaftan Beach Dress", "price": 1679, "mrp": 2269, "rating": 4, "reviews": 495, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f131", "section": "fashion", "cat": "Tops & T-shirts", "name": "Striped Boxy Tee", "price": 769, "mrp": 869, "rating": 4.8, "reviews": 2863, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f132", "section": "fashion", "cat": "Tops & T-shirts", "name": "Lace Trim Cami Top", "price": 1419, "mrp": 2029, "rating": 4.2, "reviews": 3390, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f133", "section": "fashion", "cat": "Tops & T-shirts", "name": "Button-down Cotton Shirt", "price": 609, "mrp": 879, "rating": 4.1, "reviews": 2476, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f134", "section": "fashion", "cat": "Tops & T-shirts", "name": "Square Neck Top", "price": 1129, "mrp": 1329, "rating": 4.7, "reviews": 422, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f135", "section": "fashion", "cat": "Tops & T-shirts", "name": "Knit Sweater Vest", "price": 519, "mrp": 809, "rating": 3.8, "reviews": 2229, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f136", "section": "fashion", "cat": "Tops & T-shirts", "name": "Tie-front Crop Top", "price": 1109, "mrp": 1819, "rating": 3.8, "reviews": 1637, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f137", "section": "fashion", "cat": "Tops & T-shirts", "name": "Satin Camisole", "price": 1409, "mrp": 2039, "rating": 4.2, "reviews": 983, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f138", "section": "fashion", "cat": "Tops & T-shirts", "name": "Cold Shoulder Top", "price": 629, "mrp": 689, "rating": 3.8, "reviews": 2488, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f139", "section": "fashion", "cat": "Tops & T-shirts", "name": "Henley Tee", "price": 1179, "mrp": 1839, "rating": 4.7, "reviews": 302, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f140", "section": "fashion", "cat": "Tops & T-shirts", "name": "Sleeveless Linen Top", "price": 509, "mrp": 559, "rating": 4.6, "reviews": 1411, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f141", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Fleece Pullover Hoodie", "price": 1709, "mrp": 2009, "rating": 4.7, "reviews": 1152, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f142", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Varsity Jacket", "price": 3439, "mrp": 5639, "rating": 4.1, "reviews": 319, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f143", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Faux Leather Jacket", "price": 2409, "mrp": 3129, "rating": 4.1, "reviews": 4762, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f144", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Quilted Jacket", "price": 3439, "mrp": 4779, "rating": 4.4, "reviews": 1506, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f145", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Oversized Cardigan", "price": 1759, "mrp": 2839, "rating": 4.2, "reviews": 1170, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f146", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Windbreaker Jacket", "price": 1559, "mrp": 2559, "rating": 4, "reviews": 909, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f147", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Printed Sweatshirt", "price": 1149, "mrp": 1469, "rating": 4, "reviews": 384, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f148", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Cropped Hoodie", "price": 1859, "mrp": 2299, "rating": 4.3, "reviews": 4423, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f149", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Corduroy Jacket", "price": 3349, "mrp": 4189, "rating": 4.5, "reviews": 2091, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f150", "section": "fashion", "cat": "Hoodies & Jackets", "name": "Longline Overcoat", "price": 1639, "mrp": 1859, "rating": 4.1, "reviews": 2674, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f151", "section": "fashion", "cat": "Jeans & Pants", "name": "High-rise Skinny Jeans", "price": 2279, "mrp": 3619, "rating": 4.7, "reviews": 1600, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f152", "section": "fashion", "cat": "Jeans & Pants", "name": "Flared Jeans", "price": 1289, "mrp": 1419, "rating": 4.7, "reviews": 1571, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f153", "section": "fashion", "cat": "Jeans & Pants", "name": "Distressed Boyfriend Jeans", "price": 2339, "mrp": 3199, "rating": 4.7, "reviews": 2090, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f154", "section": "fashion", "cat": "Jeans & Pants", "name": "Pleated Trousers", "price": 1699, "mrp": 2149, "rating": 4.2, "reviews": 1138, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f155", "section": "fashion", "cat": "Jeans & Pants", "name": "Paperbag Waist Pants", "price": 2289, "mrp": 3089, "rating": 4.7, "reviews": 2185, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f156", "section": "fashion", "cat": "Jeans & Pants", "name": "Parachute Pants", "price": 2419, "mrp": 3669, "rating": 4.6, "reviews": 1589, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f157", "section": "fashion", "cat": "Jeans & Pants", "name": "Cotton Chinos", "price": 1149, "mrp": 1849, "rating": 4.8, "reviews": 2199, "color": "#d9a6a0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f158", "section": "fashion", "cat": "Jeans & Pants", "name": "Printed Pyjama Pants", "price": 2169, "mrp": 2819, "rating": 4.2, "reviews": 3630, "color": "#c8cdd6", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f159", "section": "fashion", "cat": "Jeans & Pants", "name": "Denim Shorts", "price": 1089, "mrp": 1819, "rating": 3.8, "reviews": 1809, "color": "#d8b99a", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f160", "section": "fashion", "cat": "Jeans & Pants", "name": "Bootcut Jeans", "price": 1539, "mrp": 2049, "rating": 4.7, "reviews": 1217, "color": "#aebfb0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f161", "section": "fashion", "cat": "Jewellery", "name": "Gold-plated Hoop Earrings", "price": 2349, "mrp": 2639, "rating": 4.1, "reviews": 3630, "color": "#f2c9a5", "img": ""},
  {"id": "f162", "section": "fashion", "cat": "Jewellery", "name": "Pearl Pendant Necklace", "price": 2149, "mrp": 2789, "rating": 4.6, "reviews": 2631, "color": "#e9a0a8", "img": ""},
  {"id": "f163", "section": "fashion", "cat": "Jewellery", "name": "Kundan Maang Tikka", "price": 1199, "mrp": 1619, "rating": 4.3, "reviews": 1733, "color": "#cdb4c9", "img": ""},
  {"id": "f164", "section": "fashion", "cat": "Jewellery", "name": "Silver Toe Rings", "price": 2989, "mrp": 3989, "rating": 4.6, "reviews": 1254, "color": "#b9c7e0", "img": ""},
  {"id": "f165", "section": "fashion", "cat": "Jewellery", "name": "Oxidised Bangles Set", "price": 279, "mrp": 389, "rating": 4.1, "reviews": 2880, "color": "#c9d6c3", "img": ""},
  {"id": "f166", "section": "fashion", "cat": "Jewellery", "name": "Rose Gold Bracelet", "price": 2629, "mrp": 4109, "rating": 4.8, "reviews": 4496, "color": "#e3b66b", "img": ""},
  {"id": "f167", "section": "fashion", "cat": "Jewellery", "name": "Statement Cocktail Ring", "price": 2329, "mrp": 3189, "rating": 4, "reviews": 671, "color": "#d9a6a0", "img": ""},
  {"id": "f168", "section": "fashion", "cat": "Jewellery", "name": "Polki Choker Set", "price": 999, "mrp": 1259, "rating": 4.6, "reviews": 3666, "color": "#c8cdd6", "img": ""},
  {"id": "f169", "section": "fashion", "cat": "Jewellery", "name": "Hair Clip Jewellery Set", "price": 1699, "mrp": 2209, "rating": 4.4, "reviews": 2796, "color": "#d8b99a", "img": ""},
  {"id": "f170", "section": "fashion", "cat": "Jewellery", "name": "Meenakari Chandbali Earrings", "price": 299, "mrp": 339, "rating": 4.3, "reviews": 1950, "color": "#aebfb0", "img": ""},
  {"id": "f171", "section": "fashion", "cat": "Handbags", "name": "Quilted Shoulder Bag", "price": 2479, "mrp": 3589, "rating": 4.1, "reviews": 2274, "color": "#f2c9a5", "img": ""},
  {"id": "f172", "section": "fashion", "cat": "Handbags", "name": "Bucket Bag", "price": 3299, "mrp": 4339, "rating": 3.9, "reviews": 2433, "color": "#e9a0a8", "img": ""},
  {"id": "f173", "section": "fashion", "cat": "Handbags", "name": "Straw Beach Tote", "price": 3239, "mrp": 4499, "rating": 4.5, "reviews": 1363, "color": "#cdb4c9", "img": ""},
  {"id": "f174", "section": "fashion", "cat": "Handbags", "name": "Faux Leather Satchel", "price": 1959, "mrp": 3009, "rating": 3.9, "reviews": 284, "color": "#b9c7e0", "img": ""},
  {"id": "f175", "section": "fashion", "cat": "Handbags", "name": "Mini Backpack", "price": 969, "mrp": 1259, "rating": 4.4, "reviews": 4501, "color": "#c9d6c3", "img": ""},
  {"id": "f176", "section": "fashion", "cat": "Handbags", "name": "Phone Sling Pouch", "price": 1109, "mrp": 1849, "rating": 4.5, "reviews": 3868, "color": "#e3b66b", "img": ""},
  {"id": "f177", "section": "fashion", "cat": "Handbags", "name": "Evening Box Clutch", "price": 849, "mrp": 1159, "rating": 4.3, "reviews": 1588, "color": "#d9a6a0", "img": ""},
  {"id": "f178", "section": "fashion", "cat": "Handbags", "name": "Jute Shopping Bag", "price": 589, "mrp": 869, "rating": 3.9, "reviews": 2372, "color": "#c8cdd6", "img": ""},
  {"id": "f179", "section": "fashion", "cat": "Handbags", "name": "Hobo Bag", "price": 3289, "mrp": 5479, "rating": 4.3, "reviews": 886, "color": "#d8b99a", "img": ""},
  {"id": "f180", "section": "fashion", "cat": "Handbags", "name": "Card Holder Wallet", "price": 3119, "mrp": 3709, "rating": 3.8, "reviews": 2189, "color": "#aebfb0", "img": ""},
  {"id": "f181", "section": "fashion", "cat": "Footwear", "name": "Platform Sneakers", "price": 1619, "mrp": 2309, "rating": 4, "reviews": 981, "color": "#f2c9a5", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f182", "section": "fashion", "cat": "Footwear", "name": "Slip-on Canvas Shoes", "price": 2639, "mrp": 4119, "rating": 4.7, "reviews": 3065, "color": "#e9a0a8", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f183", "section": "fashion", "cat": "Footwear", "name": "Wedge Heels", "price": 1829, "mrp": 2229, "rating": 4.5, "reviews": 4677, "color": "#cdb4c9", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f184", "section": "fashion", "cat": "Footwear", "name": "Pearl Embellished Flats", "price": 2409, "mrp": 2939, "rating": 4.4, "reviews": 1829, "color": "#b9c7e0", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f185", "section": "fashion", "cat": "Footwear", "name": "Chunky Sneakers", "price": 2959, "mrp": 4929, "rating": 4, "reviews": 3330, "color": "#c9d6c3", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f186", "section": "fashion", "cat": "Footwear", "name": "Kitten Heels", "price": 1509, "mrp": 2359, "rating": 4.5, "reviews": 1505, "color": "#e3b66b", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f187", "section": "fashion", "cat": "Footwear", "name": "Leather Mules", "price": 1539, "mrp": 1999, "rating": 4, "reviews": 489, "color": "#d9a6a0", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f188", "section": "fashion", "cat": "Footwear", "name": "Gladiator Sandals", "price": 1019, "mrp": 1269, "rating": 4.2, "reviews": 4773, "color": "#c8cdd6", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f189", "section": "fashion", "cat": "Footwear", "name": "Chelsea Boots", "price": 2779, "mrp": 3519, "rating": 4, "reviews": 1550, "color": "#d8b99a", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f190", "section": "fashion", "cat": "Footwear", "name": "Classic Flip-flops", "price": 1369, "mrp": 1629, "rating": 4.2, "reviews": 4768, "color": "#aebfb0", "img": "", "opts": {"label": "UK size", "values": ["4", "5", "6", "7", "8"]}},
  {"id": "f191", "section": "fashion", "cat": "Activewear", "name": "High-waist Yoga Pants", "price": 1799, "mrp": 1979, "rating": 4.7, "reviews": 2007, "color": "#f2c9a5", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f192", "section": "fashion", "cat": "Activewear", "name": "Seamless Sports Bra", "price": 1979, "mrp": 2169, "rating": 4.2, "reviews": 3847, "color": "#e9a0a8", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f193", "section": "fashion", "cat": "Activewear", "name": "Dry-fit Running Tee", "price": 2409, "mrp": 3349, "rating": 4.6, "reviews": 585, "color": "#cdb4c9", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f194", "section": "fashion", "cat": "Activewear", "name": "Cycling Shorts", "price": 1679, "mrp": 2429, "rating": 3.8, "reviews": 633, "color": "#b9c7e0", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f195", "section": "fashion", "cat": "Activewear", "name": "Zip Track Jacket", "price": 1279, "mrp": 1639, "rating": 4.1, "reviews": 839, "color": "#c9d6c3", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f196", "section": "fashion", "cat": "Activewear", "name": "Gym Tank Top", "price": 739, "mrp": 889, "rating": 4.2, "reviews": 1336, "color": "#e3b66b", "img": "", "opts": {"label": "Size", "values": ["S", "M", "L", "XL"]}},
  {"id": "f197", "section": "fashion", "cat": "Activewear", "name": "Resistance Band Set", "price": 579, "mrp": 709, "rating": 3.8, "reviews": 4560, "color": "#d9a6a0", "img": ""},
  {"id": "f198", "section": "fashion", "cat": "Activewear", "name": "Sports Water Bottle", "price": 1169, "mrp": 1689, "rating": 3.8, "reviews": 3270, "color": "#c8cdd6", "img": ""},
  {"id": "f199", "section": "fashion", "cat": "Activewear", "name": "Skipping Rope", "price": 2089, "mrp": 2349, "rating": 4.2, "reviews": 2931, "color": "#d8b99a", "img": ""},
  {"id": "f200", "section": "fashion", "cat": "Activewear", "name": "Fitness Gloves", "price": 1839, "mrp": 2109, "rating": 4, "reviews": 1028, "color": "#aebfb0", "img": ""}
);
